classdef IALiRT < mag.graphics.view.Science
% IALiRT Show IALiRT.

    methods

        function this = IALiRT(results, options)

            arguments
                results
                options.?mag.graphics.view.IALiRT
            end

            this.Results = results;

            this.assignProperties(options);
        end

        function visualize(this)

            this.Figures = matlab.ui.Figure.empty();

            primaryIALiRT = this.Results.IALiRT.Primary;
            secondaryIALiRT = this.Results.IALiRT.Secondary;

            % Plot only I-ALiRT.
            this.Figures(1) = mag.graphics.visualize( ...
                primaryIALiRT, mag.graphics.style.Stackedplot(Title = this.getFieldTitle(primaryIALiRT), YLabels = ["x [nT]", "y [nT]", "z [nT]", "|B| [nT]"], Charts = mag.graphics.chart.Stackedplot(YVariables = ["X", "Y", "Z", "B"])), ...
                secondaryIALiRT, mag.graphics.style.Stackedplot(Title = this.getFieldTitle(secondaryIALiRT), YLabels = ["x [nT]", "y [nT]", "z [nT]", "|B| [nT]"], Charts = mag.graphics.chart.Stackedplot(YVariables = ["X", "Y", "Z", "B"])), ...
                Title = this.getFigureTitle(primaryIALiRT, secondaryIALiRT), ...
                Name = this.getFigureName(primaryIALiRT, secondaryIALiRT), ...
                Arrangement = [1, 2], ...
                LinkXAxes = true, ...
                WindowState = "maximized");

            % Plot I-ALiRT and science.
            defaultColors = colororder();

            primaryScience = this.Results.Primary;
            secondaryScience = this.Results.Secondary;

            primaryComparison = synchronize(timetable(primaryIALiRT.Time, primaryIALiRT.X, primaryIALiRT.Y, primaryIALiRT.Z, VariableNames = ["xi", "yi", "zi"]), ...
                timetable(primaryScience.Time, primaryScience.X, primaryScience.Y, primaryScience.Z, VariableNames = ["xs", "ys", "zs"]), "first", "nearest");
            secondaryComparison = synchronize(timetable(secondaryIALiRT.Time, secondaryIALiRT.X, secondaryIALiRT.Y, secondaryIALiRT.Z, VariableNames = ["xi", "yi", "zi"]), ...
                timetable(secondaryScience.Time, secondaryScience.X, secondaryScience.Y, secondaryScience.Z, VariableNames = ["xs", "ys", "zs"]), "first", "nearest");

            this.Figures(2) = mag.graphics.visualize( ...
                primaryComparison, ...
                [mag.graphics.style.Default(Title = this.getFieldTitle(primaryIALiRT), YLabel = "x [nT]", Layout = [2, 1], Charts = [mag.graphics.chart.Plot(YVariables = "xs", Marker = "o"), mag.graphics.chart.Plot(YVariables = "xi", Marker = "x")]), ...
                mag.graphics.style.Default(YLabel = "\Deltax [nT]", Charts = mag.graphics.chart.Plot(YVariables = mag.graphics.operation.Difference(Minuend = "xs", Subtrahend = "xi"), Colors = defaultColors(3, :))), ...
                mag.graphics.style.Default(YLabel = "y [nT]", Layout = [2, 1], Charts = [mag.graphics.chart.Plot(YVariables = "ys", Marker = "o"), mag.graphics.chart.Plot(YVariables = "yi", Marker = "x")]), ...
                mag.graphics.style.Default(YLabel = "\Deltay [nT]", Charts = mag.graphics.chart.Plot(YVariables = mag.graphics.operation.Difference(Minuend = "ys", Subtrahend = "yi"), Colors = defaultColors(3, :))), ...
                mag.graphics.style.Default(YLabel = "z [nT]", Layout = [2, 1], Charts = [mag.graphics.chart.Plot(YVariables = "zs", Marker = "o"), mag.graphics.chart.Plot(YVariables = "zi", Marker = "x")]), ...
                mag.graphics.style.Default(YLabel = "\Deltaz [nT]", Charts = mag.graphics.chart.Plot(YVariables = mag.graphics.operation.Difference(Minuend = "zs", Subtrahend = "zi"), Colors = defaultColors(3, :)))], ...
                secondaryComparison, ...
                [mag.graphics.style.Default(Title = this.getFieldTitle(secondaryIALiRT), YLabel = "x [nT]", Layout = [2, 1], Charts = [mag.graphics.chart.Plot(YVariables = "xs", Marker = "o"), mag.graphics.chart.Plot(YVariables = "xi", Marker = "x")]), ...
                mag.graphics.style.Default(YLabel = "\Deltax [nT]", Charts = mag.graphics.chart.Plot(YVariables = mag.graphics.operation.Difference(Minuend = "xs", Subtrahend = "xi"), Colors = defaultColors(3, :))), ...
                mag.graphics.style.Default(YLabel = "y [nT]", Layout = [2, 1], Charts = [mag.graphics.chart.Plot(YVariables = "ys", Marker = "o"), mag.graphics.chart.Plot(YVariables = "yi", Marker = "x")]), ...
                mag.graphics.style.Default(YLabel = "\Deltay [nT]", Charts = mag.graphics.chart.Plot(YVariables = mag.graphics.operation.Difference(Minuend = "ys", Subtrahend = "yi"), Colors = defaultColors(3, :))), ...
                mag.graphics.style.Default(YLabel = "z [nT]", Layout = [2, 1], Charts = [mag.graphics.chart.Plot(YVariables = "zs", Marker = "o"), mag.graphics.chart.Plot(YVariables = "zi", Marker = "x")]), ...
                mag.graphics.style.Default(YLabel = "\Deltaz [nT]", Charts = mag.graphics.chart.Plot(YVariables = mag.graphics.operation.Difference(Minuend = "zs", Subtrahend = "zi"), Colors = defaultColors(3, :)))], ...
                Title = "Science vs. I-ALiRT", ...
                Name = "Science vs. I-ALiRT", ...
                Arrangement = [9, 2], ...
                GlobalLegend = ["Science", "I-ALiRT"], ...
                LinkXAxes = true, ...
                TileIndexing = "columnmajor", ...
                WindowState = "maximized");
        end
    end
end
